dh_1~6
Suyeon-B/week03_team pull request #1
Opened 2022-04-15 14:01 UTC by dd0114

아직 다 못품!

2022-04-15 15:13 UTC, Suyeon-B requested changes
오늘 스터디 내용으로 코드 업뎃 후 한 번 더 commit, push, PR 해주세용〰️ 👍

2022-04-15 15:13 UTC, Suyeon-B commented on dd0114/01_1991.py
> +    tree[n] = Node(key=n, left=l, right= r)
Node(key=n, left=l, right=r) 이라고 써도 되고,
Node(n, l, r) 요렇게 써도 됩니당〰️! 😄

2022-04-15 15:13 UTC, Suyeon-B commented on dd0114/01_1991.py
> +    # 트리 딕셔너리에 저장한다는 뜻인데 node가 의미하는 것은? 각 노드의 이름?
n 의 의미는 l, r의 parent입니다〰️

2022-04-15 15:13 UTC, Suyeon-B commented on dd0114/01_1991.py
> +print(preorder(tree['A']))
print 함수에 대해 한 번 더 생각하게 되었어요!
굳굳 ㅎㅎ

2022-04-17 06:45 UTC, connieya commented on dd0114/01_1991.py
> +    # 트리 딕셔너리에 저장한다는 뜻인데 node가 의미하는 것은? 각 노드의 이름?
key 값이 없어도 순회한 결과를 출력할 수 있어요 key 값 없는 버전으로 한번 수정해보세요 ^^

2022-04-17 06:45 UTC, connieya commented on dd0114/01_1991.py
> +print()
print() 함수를 한 번 더 사용하지 않아도 됩니다. ^^

2022-04-17 06:45 UTC, connieya commented on dd0114/07_11725.py
> +    print(parent[i])
LGTM !

2022-04-17 06:45 UTC, connieya commented on dd0114/08_1707.py
> +        print('NO')
이분 탐색 그래프인지 확인할 때  breaker 로 판단해도 될 것 같아요.  (count 변수는 없어도 될 것 같아요 ^^)

2022-04-17 06:45 UTC, connieya commented on dd0114/09_21606.py
> +print (count)
inout 변수로 입력 받을 때 '0' 을 추가한 부분 너무 좋네요 ^^

2022-04-17 06:45 UTC, connieya commented on dd0114/09_21606.py
> +print (count)
시간 초과가 나지 않으려면 다른 방식으로 접근을 해야 할 것 같아요 !!!!

2022-04-17 06:45 UTC, connieya commented on dd0114/10_14888_re.py
> +print(minimum)
div () 함수로 분리해서 가독성이 좋네요 !!  
int( result // Alist[count] ) 을 사용하시면 직접 구현 안하셔도 되긴 해요 !!

2022-04-18 12:26 UTC, merged